'use client'
import { FileText, Printer } from 'lucide-react'
import { Player } from '../types'

interface Props {
  teamA: Player[]
  teamB: Player[]
}

const POSITION_ORDER = [3, 4, 2, 1]
const POSITION_LABELS: Record<number, string> = {
  1: 'Forward',
  2: 'Midfielder',
  3: 'Pivot',
  4: 'Back',
}

function assignPositions(players: Player[]): { pos: number; player: Player | null }[] {
  const sorted = [...players].sort((a, b) => b.handicap - a.handicap)
  const orderMap = [3, 4, 2, 1]
  return POSITION_ORDER.map((pos) => ({
    pos,
    player: sorted[orderMap.indexOf(pos)] ?? null,
  }))
}

export default function MatchSummary({ teamA, teamB }: Props) {
  if (teamA.length === 0 && teamB.length === 0) {
    return (
      <div className="card">
        <h2 className="text-lg font-bold text-amber-400 flex items-center gap-2 mb-2">
          <FileText size={20} /> Match Summary
        </h2>
        <p className="text-slate-500 text-sm text-center py-4">Set up your teams to generate a match summary card.</p>
      </div>
    )
  }

  const hcpA = teamA.reduce((s, p) => s + p.handicap, 0)
  const hcpB = teamB.reduce((s, p) => s + p.handicap, 0)
  const diff = Math.abs(hcpA - hcpB)
  const lowerTeam = hcpA <= hcpB ? 'Team A' : 'Team B'
  const posA = assignPositions(teamA)
  const posB = assignPositions(teamB)

  return (
    <div className="card space-y-4" id="match-summary">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-bold text-amber-400 flex items-center gap-2">
          <FileText size={20} /> Match Summary
        </h2>
        <button className="btn-secondary flex items-center gap-1 text-xs" onClick={() => window.print()}>
          <Printer size={13} /> Print
        </button>
      </div>

      {/* Head start banner */}
      {diff > 0 && (
        <div className="bg-amber-500/20 border border-amber-500/50 rounded-xl px-4 py-3 text-center">
          <p className="text-amber-300 text-sm font-semibold">
            🏇 {lowerTeam} starts with a <span className="text-amber-400 font-black text-lg">{diff}</span>-goal advantage
          </p>
        </div>
      )}
      {diff === 0 && (
        <div className="bg-emerald-500/20 border border-emerald-500/50 rounded-xl px-4 py-3 text-center">
          <p className="text-emerald-300 text-sm font-semibold">⚡ Even match — no head start required</p>
        </div>
      )}

      {/* Team cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {[
          { label: 'Team A', hcp: hcpA, positions: posA, color: 'text-blue-400', border: 'border-blue-700' },
          { label: 'Team B', hcp: hcpB, positions: posB, color: 'text-purple-400', border: 'border-purple-700' },
        ].map(({ label, hcp, positions, color, border }) => (
          <div key={label} className={`border ${border} rounded-xl p-4 space-y-3 bg-slate-800/60`}>
            <div className={`font-black text-lg ${color}`}>
              {label} <span className="text-slate-400 font-normal text-sm">{hcp} HCP total</span>
            </div>
            <div className="space-y-1.5">
              {positions.map(({ pos, player }) => (
                <div key={pos} className="flex justify-between items-center text-sm">
                  <span className="text-slate-400 w-24">#{pos} {POSITION_LABELS[pos]}</span>
                  {player ? (
                    <span className="font-medium">
                      {player.name} <span className="text-amber-400 text-xs">{player.handicap > 0 ? `+${player.handicap}` : player.handicap}</span>
                    </span>
                  ) : (
                    <span className="text-slate-600 text-xs">Unassigned</span>
                  )}
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      <p className="text-xs text-slate-600 text-center">Generated by PoloIQ · poloiq.vercel.app</p>
    </div>
  )
}
